@startuml usercase
    left to right direction


    skinparam usecase {
        BackgroundColor LightGreen
        BorderColor Blue
        BackgroundColor<<main>> MistyRose
        BackgroundColor<<Entity>> MistyRose
    }

    actor  "ユーザー"
    actor "店舗情報管理者"

    package "店舗商品検索システム" {

        rectangle "店舗管理者のアカウント"{
            usecase  "店舗管理者のアカウントを、\n登録・変更・削除する"
        }
        rectangle "エンティティの操作" {
            rectangle "エンティティの登録・変更・削除操作"{
                usecase  "エンティティを\n登録・変更・削除する"
                usecase  "文字情報を\n登録・変更・削除する"
                usecase  "画像情報を\n登録・変更・削除する"
            }

            usecase  "既存エンティティを検索する"
        }

        rectangle "店舗エンティティの操作" {
             rectangle "店舗エンティティの登録操作"{
                usecase  "店舗を\n登録・変更・削除する"
                usecase  "店舗の文字情報を\n登録・変更・削除する"
                usecase  "店舗画像の\n登録・変更・削除する"
             }
            usecase  "既存店舗を検索する"
        }

        rectangle "商品エンティティの操作"{
             rectangle "商品エンティティの登録・変更・削除操作"{
                usecase  "商品エンティティの\n登録・変更・削除する"
                usecase  "商品の文字情報を\n登録・変更・削除する"
                usecase  "商品画像の\n登録・変更・削除する"
             }
            usecase  "既存商品を検索する"
        }

        rectangle "座標設定"{
            usecase  "店内地図を\n登録・変更・削除する"
            usecase  "店内地図に、座標を登録・変更・削除する"
            usecase  "店内地図に、点座標を登録・変更・削除する"
            usecase  "店内地図に、面積座標を登録・変更・削除する"
            usecase  "座標と、商品の関係性について、登録・変更・削除をする。"
        }

        usecase  "商品がある店舗調べる"

    }



    'アクターと、主要なユースケースとの関係
    ユーザー -down-> (商品がある店舗調べる)
    店舗情報管理者 -down-> (店舗管理者のアカウントを、\n登録・変更・削除する)
    店舗情報管理者 -down-> (店舗を\n登録・変更・削除する)
    店舗情報管理者 -down-> (商品エンティティの\n登録・変更・削除する)

    'ユースケースの継承の関係：エンティティ作成に対して
    (エンティティを\n登録・変更・削除する) ..> (店舗を\n登録・変更・削除する) : <<extends>>
    (エンティティを\n登録・変更・削除する) .left.> (商品エンティティの\n登録・変更・削除する) : <<extends>>

    'ユースケースの包括関係：エンティテ作成に対して
    (店舗管理者のアカウントを、\n登録・変更・削除する) ..> (エンティティを\n登録・変更・削除する) : <<include>>
    (エンティティを\n登録・変更・削除する) ..> (画像情報を\n登録・変更・削除する) : <<include>>
    (エンティティを\n登録・変更・削除する) ..> (文字情報を\n登録・変更・削除する) : <<include>>
    (エンティティを\n登録・変更・削除する) -up- (既存エンティティを検索する)

    '関係設定：店舗エンティティの操作内に対して
    (店舗を\n登録・変更・削除する) ..> (店舗の文字情報を\n登録・変更・削除する) : <<include>>
    (店舗を\n登録・変更・削除する) ..> (店舗画像の\n登録・変更・削除する) : <<include>>
    (店舗を\n登録・変更・削除する)-up- (既存店舗を検索する)

    '関係設定：商品エンティティの操作内に対して
    (商品エンティティの\n登録・変更・削除する) ..> (商品の文字情報を\n登録・変更・削除する) : <<include>>
    (商品エンティティの\n登録・変更・削除する) ..> (商品画像の\n登録・変更・削除する) : <<include>>
    (商品エンティティの\n登録・変更・削除する) -left- (既存商品を検索する)


    '関係設定：座標設定とそれ以外の要素との関係
    (店舗を\n登録・変更・削除する) -down- (店内地図を\n登録・変更・削除する)
    (商品エンティティの\n登録・変更・削除する) -right- (座標と、商品の関係性について、登録・変更・削除をする。)

    '関係設定：座標設定内に対して
    (店内地図を\n登録・変更・削除する) -down-> (店内地図に、座標を登録・変更・削除する) : <<include>>
    (店内地図に、座標を登録・変更・削除する) .left.> (店内地図に、点座標を登録・変更・削除する) : <<extends>>
    (店内地図に、座標を登録・変更・削除する) .left.> (店内地図に、面積座標を登録・変更・削除する) : <<extends>>
    (店内地図を\n登録・変更・削除する) .left.> (座標と、商品の関係性について、登録・変更・削除をする。) : <<include>>


    note "特定の要素を絞り込み検索で、\nより扱いやすくする" as noteOfSearch
    noteOfSearch .down. (既存エンティティを検索する)
@enduml
